import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono, Alegreya_Sans} from "next/font/google";
=======
import { Geist, Geist_Mono, Alegreya_Sans } from "next/font/google";
>>>>>>> 536c354a443cd2c3ca23460b3ec6c2c2e8f6cfc5
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const alegreyaSans = Alegreya_Sans({
  variable: "--font-alegreya-sans",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< HEAD
const alegreya_sans = Alegreya_Sans({
  variable: "--font-alegreya-sans",
  subsets: ["latin"],
  weight: "100"
=======
const AlegreyaSans = Alegreya_Sans({
  variable: "--font-alegreya-sans",
  subsets: ["latin"],
  weight: "100",
>>>>>>> 536c354a443cd2c3ca23460b3ec6c2c2e8f6cfc5
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const alegreya_Sans = Alegreya_Sans({
  variable: "--font-alegreya-sans",
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} ${alegreya_sans.variable} antialiased`}
=======
        className={`${geistSans.variable} ${geistMono.variable} ${alegreyaSans.variable} antialiased`}
>>>>>>> 536c354a443cd2c3ca23460b3ec6c2c2e8f6cfc5
      >
        {children}
      </body>
    </html>
  );
}
